# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 07:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='timeStamp',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 5, 7, 33, 18, 990065, tzinfo=utc), verbose_name='时间戳'),
            preserve_default=False,
        ),
    ]
